version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: actualbudget_web_1
      APP_PORT: 5006

  web:
    image: actualbudget/actual-server:23.6.0@sha256:bd0d7b4febf8d79e6dd450c103aadac3b973c307a33bfad92c52e3e38600733b
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/:/data
